[package]
name = "citymodelgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
fastlem = "0.1.3"
noise = "0.8"
image = "0.24"